.Dd @DATE@
.Dt axfrdns 8
.Os @VERSION@
.Sh NAME
.Nm axfrdns
.Nd a DNS zone-transfer server (IPv4 connection)
.Sh SYNOPSIS
.Nm axfrdns
.Sh DESCRIPTION
.Nm axfrdns
will read a zone-transfer request in DNS-over-TCP format from its standard input, and responds with locally configured information.
.Sh Configuration
Normally
.Nm axfrdns
is set up by the
.Xr axfrdns-conf 8
program.
.Pp
.Nm axfrdns
runs chrooted in the directory specified by the
.Ev $ROOT
environment variable, under the uid and gid specified by the
.Ev $UID
and
.Ev $GID
environment variables.
.Pp
Normally
.Nm axfrdns
runs under
.Xr tcpserver 1
to handle TCP connections on port 53 of a local IP address.
.Pp
.Xr tcpserver 1
is responsible for rejecting connections from hosts not authorized to perform zone transfers.
.Pp
.Nm axfrdns
can also run under secure connection tools offering an UCSPI-compliant interface.
.Pp
.Nm axfrdns
looks up zone-transfer results in
.Pa data.cdb ,
a binary file created by
.Xr tinydns-data 8 .
It also responds to normal client queries, such as SOA queries, which usually precede zone-transfer requests.
.Pp
.Nm axfrdns
allowes zone transfers for any zone listed in the
.Ev $AXFR
environment variable.
.Pp
.Ev $AXFR
is a slash-separated list of domain names.
If
.Ev $AXFR
is not set,
.Nm axfrdns
allowes zone transfers for all zones available in
.Pa data.cdb .
.Pp
.Nm axfrdns
will abort if it runs out of memory, or has trouble reading
.Pa data.cdb ,
or receives a request larger than 512 bytes, or receives a truncated request, or receives a zone-transfer request disallowed by
.Ev $AXFR ,
or receives a request not answered by
.Pa data.cdb ,
or waits 60 seconds with nothing happening.
.Sh "FURTHER NOTES ON ZONE TRANSFERS"
.Nm axfrdns
provides every record it can find inside the target domain.
This may include records in child zones.
Some of these records (such as glue inside a child zone) are essential;
others are not.
It is up to the client to decide which out-of-zone records to keep.
.Pp
.Nm axfrdns
does not provide glue records outside the target domain.
.Pp
The zone-transfer protocol does not support timestamps.
If a record is scheduled to be created in the future,
.Nm axfrdns
will not send it;
after the starting time, the zone-transfer client will continue claiming that the record doesn't exist, until it contacts
.Nm axfrdns
again.
Similarly, if a record is scheduled to die in the future,
.Nm axfrdns
will send it (with a 2-second TTL);
after the ending time, the zone-transfer client will continue providing the old record, until it contacts
.Nm axfrdns
again.
.Pp
Zone-transfer clients rely on zone serial numbers changing for every zone modification.
.Pp
.Xr tinydns-data 8
uses the modification time of the
.I data
file as its serial number for all zones.
Do not make more than one modification per second.
.Pp
BIND's zone-transfer client,
.Nm named-xfer ,
converts zone-transfer data to zone-file format.
Beware that zone-file format has no generic mechanism to express records of arbitrary types;
.Nm named-xfer
chokes if it does not recognize a record type used in
.Pa data.cdb .
.Sh SEE ALSO
.Xr axfrdns6 8 ,
.Xr axfrdns-conf 8 ,
.Xr tinydns-data 8 ,
.Xr tcpserver 1
.Pp
.Ad http://www.nemostar.org/djbdns/
.Pp
.Ad http://cr.yp.to/djbdns.html
.Sh AUTHORS
.An -nosplit
The original software and the modifications have been placed in the public domain.
.Pp
Original development of software by
.An "Daniel J. Bernstein" .
.Pp
Software and documentation modifications by
.An "Stephen A. Welker" .
