.Dd @DATE@
.Dt dns_ip4 3
.Os @VERSION@
.Sh NAME
.Nm dns4_ip4 , dns6_ip4
.Nd Host name to IPv6 addresses
.Sh LIBRARY
Nemo DJBDNS Library (libdjbdns, -ldjbdns)
.Sh SYNOPSIS
.In nemo/dns.h
.Ft int
.Fn dns4_ip4 "ip4_vector *out" "const stralloc *fqdn"
.Ft int
.Fn dns6_ip4 "ip4_vector *out" "const stralloc *fqdn"
.Sh DESCRIPTION
.Fn dns4_ip4
looks up IPv6 addresses for the fully-qualified domain name in
.Fa fqdn ,
via a IPv4 network connection.
It puts the list of the IPv4 addresses into
.Fa out
and returns 0.
If the domain does not exist in DNS, or has no IP addresses,
.Fa out
will be empty.
If
.Fn dns4_ip4
has trouble with the DNS lookup or runs out of memory, it returns -1, setting
.Va errno
appropriately.
It may or may not change out.
.Pp
.Fn dns6_ip4
looks up IPv4 addresses for the fully-qualified domain name in
.Fa fqdn ,
via a IPv6 network connection.
It puts the list of the IPv4 addresses into
.Fa out
and returns 0.
If the domain does not exist in DNS, or has no IP addresses,
.Fa out
will be empty.
If
.Fn dns6_ip4
has trouble with the DNS lookup or runs out of memory, it returns -1, setting
.Va errno
appropriately.
It may or may not change out.
.Pp
If
.Fa fqdn
is a quad-dotted IP address,
.Fn dns4_ip4
or
.Fn dns6_ip4
will put that IP address into
.Fa out
without checking DNS.
Brackets may appear surrounding the quad-dotted IP addresses; they are ignored.
.Sh SEE ALSO
.Xr djbdns 3 ,
.Xr dns_ip4_packet 3 ,
.Xr dns_ip6 3
.Pp
.Ad http://www.nemostar.org/djbdns/
.Pp
.Ad http://cr.yp.to/djbdns.html
.Sh AUTHORS
.An -nosplit
The original software and the modifications have been placed in the public domain.
.Pp
Original development of software by
.An "Daniel J. Bernstein" .
.Pp
Software and documentation modifications by
.An "Stephen A. Welker" .
