.Dd @DATE@
.Dt dns_ns_packet 3
.Os @VERSION@
.Sh NAME
.Nm dns_ns_packet
.Nd low level packet manipulation of NS records
.Sh LIBRARY
Nemo DJBDNS Library (libdjbdns, -ldjbdns)
.Sh SYNOPSIS
.In nemo/dns.h
.Ft int
.Fn dns_ns_packet "sa_vector *out" "const byte_t *buf" "unsigned int len"
.Sh DESCRIPTION
.Fn dns_ns_packet is a low-level component of
.Xr dns4_ns 3
and
.Xr dns6_ns 3 ,
designed to support asynchronous DNS lookups.
It reads a DNS packet of length
.Fa len
from
.Fa buf ,
extracts the all NS records from the answer section of the packet, puts the results into
.Fa out ,
and returns 0 or -1 the same way as
.Xr dns4_ns 3
or
.Xr dns6_ns 3 .
.Sh SEE ALSO
.Xr djbdns 3 ,
.Xr dns4_ns 3
.Xr dns6_ns 3
.Pp
.Ad http://www.nemostar.org/djbdns/
.Pp
.Ad http://cr.yp.to/djbdns.html
.Sh AUTHORS
.An -nosplit
The original software and the modifications have been placed in the public domain.
.Pp
Original development of software by
.An "Daniel J. Bernstein" .
.Pp
Software and documentation modifications by
.An "Stephen A. Welker" .
