.Dd @DATE@
.Dt dns_ip6_packet 3
.Os @VERSION@
.Sh NAME
.Nm dns_ip6_packet
.Nd low level packet manipulation of AAAA records for a domain
.Sh LIBRARY
Nemo DJBDNS Library (libdjbdns, -ldjbdns)
.Sh SYNOPSIS
.In nemo/dns.h
.Ft int
.Fn dns_ip6_packet "ip6_vector *out" "const byte_t *buf" "unsigned int len"
.Sh DESCRIPTION
.Fn dns_ip6_packet
is a low-level component of
.Fn dns4_ip6
and
.Fn dns6_ip6 ,
designed to support asynchronous DNS lookups.
It reads a DNS packet of length
.Fa len
from
.Fa buf ,
extracts IPv6 addresses from the answer section of the packet, puts the addresses into
.Fa out ,
and returns 0 or -1 the same way as the routines
.Fn dns4_ip6
or
.Fn dns6_ip6 .
.Sh SEE ALSO
.Xr djbdns 3 ,
.Xr dns_ip6 3
.Xr dns_ip4 3
.Pp
.Ad http://www.nemostar.org/djbdns/
.Pp
.Ad http://cr.yp.to/djbdns.html
.Sh AUTHORS
.An -nosplit
The original software and the modifications have been placed in the public domain.
.Pp
Original development of software by
.An "Daniel J. Bernstein" .
.Pp
Software and documentation modifications by
.An "Stephen A. Welker" .
