.Dd @DATE@
.Dt dnsip 1
.Os @VERSION@
.Sh NAME
.Nm dnsip
.Nd lookup IPv4 addresses
.Sh SYNOPSIS
.Nm dnsip
.Op Fl 46
.Op Ar fqdn ...
.Sh DESCRIPTION
.Nm dnsip
resolves
.Ar fqdn
and prints the IPv4 addresses of
.Ar fqdn
on a single line.
If
.Ar fqdn
does not exist,
.Nm dnsip
prints a blank line.
You can list several
.Ar fqdn Ns Li s;
.Nm dnsip
prints each result on a separate line.
.Sh "OPTIONS"
.Bl -tag
.It Fl 4
(Default). Connect to the network using IPv4.
.It Fl 6
Connect to the network using IPv6.
.El
.Sh DIAGNOSTICS
Normally
.Nm dnsip
exits 0.
If
.Nm dnsip
encounters a temporary problem that prevents it from determining the list of IPv4 addresses, it prints an error message and exits 111.
The same comments apply to the other programs described here.
.Sh SEE ALSO
.Xr dnsip6 1 ,
.Xr dnsipq 1 ,
.Xr dnsname 1 ,
.Xr dnsmx 1 ,
.Xr dnstxt 1 ,
.Xr dnsqr 1 ,
.Xr dnsq 1 ,
.Xr dnstrace 1
.Pp
.Ad http://www.nemostar.org/djbdns/
.Pp
.Ad http://cr.yp.to/djbdns.html
.Sh AUTHORS
.An -nosplit
The original software and the modifications have been placed in the public domain.
.Pp
Original development of software by
.An "Daniel J. Bernstein" .
.Pp
Software and documentation modifications by
.An "Stephen A. Welker" .
