.Dd @DATE@
.Dt dnsmxip 1
.Os @VERSION@
.Sh NAME
.Nm dnsmxip
.Nd prints the (IPv4) MX records of a fqdn
.Sh SYNOPSIS
.Nm dnsmxip
.Op Fl 46
.Ar fqdn
.Sh DESCRIPTION
.Nm dnsmxip
prints the MX records of
.Ar fqdn .
If there are no MX records,
.Nm dnsmxip
prints an artificial MX record, simulating the behavior of MTAs.
.Sh "OPTIONS"
.Bl -tag
.It Fl 4
(Default). Connect to the network using IPv4.
.It Fl 6
Connect to the network using IPv6.
.El
.Sh DIAGNOSTICS
Normally
.Nm dnsmxip
exits 0.
If
.Nm dnsmxip
encounters a temporary problem that prevents it from determining the list of MX records, it prints an error message and exits 111.
.Sh SEE ALSO
.Xr dnsip 1 ,
.Xr dnsip6 1 ,
.Xr dnsmx 1 ,
.Xr dnsname 1 ,
.Xr dnsipq 1 ,
.Xr dnsip6q 1 ,
.Xr dnstxt 1 ,
.Xr dnsqr 1 ,
.Xr dnsq 1 ,
.Xr dnstrace 1
.Pp
.Ad http://www.nemostar.org/djbdns/
.Pp
.Ad http://cr.yp.to/djbdns.html
.Sh AUTHORS
.An -nosplit
The original software and the modifications have been placed in the public domain.
.Pp
Original development of software by
.An "Daniel J. Bernstein" .
.Pp
Software and documentation modifications by
.An "Stephen A. Welker" .
