.Dd @DATE@
.Dt dnsq 1
.Os @VERSION@
.Sh NAME
.Nm dnsq
.Nd sends a non-recursive DNS query to DNS server
.Sh SYNOPSIS
.Nm dnsq
.Op Fl 46
.Ar t
.Ar fqdn
.Ar s
.Sh DESCRIPTION
.Nm dnsq
sends a non-recursive DNS query to DNS server
.Ar s
for records of type
.Ar t
under the domain name
.Ar fqdn .
It prints the results in a human-readable format.
.Sh "OPTIONS"
.Bl -tag
.It Fl 4
(Default). Connect to the network using IPv4.
.It Fl 6
Connect to the network using IPv6.
.El
.Sh SEE ALSO
.Xr dnsip 1 ,
.Xr dnsip6 1 ,
.Xr dnsipq 1 ,
.Xr dnsmx 1 ,
.Xr dnstxt 1 ,
.Xr dnsqr 1 ,
.Xr dnsname 1 ,
.Xr dnstrace 1 ,
.Xr tinydns-get 1
.Pp
.Ad http://www.nemostar.org/djbdns/
.Pp
.Ar http://cr.yp.to/djbdns.html
.Sh AUTHORS
.An -nosplit
The original software and the modifications have been placed in the public domain.
.Pp
Original development of software by
.An "Daniel J. Bernstein" .
.Pp
Software and documentation modifications by
.An "Stephen A. Welker" .
