.Dd @DATE@
.Dt dnstracesort 1
.Os @VERSION@
.Sh NAME
.Nm dnstrace sort
.Nd convert the output of
.Xr dnstrace 1
into human-friendly output
.Sh SYNOPSIS
.Nm dnstracesort
.Sh DESCRIPTION
Normally
.Nm dnstracesort
is connected by a pipe to the output of
.Xr dnstrace 1
so that it nay convert the output of
.Xr dnstrace 1
into human-friendly output.
.Sh SEE ALSO
.Xr dnstrace 1
.Pp
.Ad http://www.nemostar.org/djbdns/
.Pp
.Ad http://cr.yp.to/djbdns.html
.Sh AUTHORS
.An -nosplit
The original software and the modifications have been placed in the public domain.
.Pp
Original development of software by
.An "Daniel J. Bernstein" .
.Pp
Software and documentation modifications by
.An "Stephen A. Welker" .
