.Dd @DATE@
.Dt tinydns6-conf 8
.Os @VERSION@
.Sh NAME
.Nm tinydns6-conf
.Nd sets up a DNS publication service (IPv6 network connection)
.Sh SYNOPSIS
.Nm tinydns6-conf
.Ar acct
.Ar logacct
.Ar D
.Ar ip
.Sh DESCRIPTION
.Nm tinydns6-conf
creates a service directory
.Ar D
that runs
.Xr tinydns6 8 .
The name
.Ar D
must start with a slash and must not contain any special characters.
Normally
.Ar D
is
.Pa /etc/tinydns6 .
.Pp
You can run the service under
.Xr svscan 8
by creating a symbolic link in the
.Xr svscan 8
directory:
.Pp
.Dl "ln \-s" Ar D Ns Pa /service
.Pp
The service will start within five seconds, and will be restarted upon reboot.
You can use
.Xr svctl 8
to control the service.
.Pp
.Nm tinydns6-conf
arranges for
.Xr tinydns6 8
to chroot to
.Ar D Ns Pa /root
and to run under the uid and gid of
.Ar acct .
The name
.Ar acct
must not contain any special characters.
.Pp
.Nm tinydns6-conf
creates
.Ar D Ns Pa /root/Makefile
to run
.Xr tinydns-data 8
upon request.
.Pp
.Nm tinydns6-conf
arranges for
.Xr tinydns6 8
to listen for UDP packets on port 53 of
.Ar ip ,
and to send outgoing packets from
.Ar ip .
.Pp
.Nm tinydns6-conf
creates an automatically rotated log directory in
.Ar D Ns Pa /log/main .
The logs are owned by
.Ar logacct .
The corresponding
.Ar multilog 8
processes run under the uid and gid of
.Ar logacct .
The name
.Ar logacct
must not contain any special characters.
.Sh EXAMPLES
For tutorial information, see the instructions for running a DNS server:
.Pp
.Ad http://cr.yp.to/djbdns/run-server.html
.Sh SEE ALSO
.Xr tinydns6 8 ,
.Xr svscan 8 ,
.Xr svctl 8 ,
.Xr multilog 8 ,
.Xr axfrdns-conf 8 ,
.Xr rbldns-conf 8 ,
.Xr dnscache-conf 8 ,
.Xr walldns-conf 8
.Pp
.Ad http://www.nemostar.org/djbdns/
.Pp
.Ad http://cr.yp.to/djbdns.html
.Sh AUTHORS
.An -nosplit
The original software and the modifications have been placed in the public domain.
.Pp
Original development of software by
.An "Daniel J. Bernstein" .
.Pp
Software and documentation modifications by
.An "Stephen A. Welker" .
